version: '3'
services:
  #部署nginx
  nginx:
   container_name: v-nginx
   image: nginx
   restart: always
   ports:
   - 80:80
   - 443:443
  #反向代理配置文件
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
    
  mysql:
   container_name: v-mysql
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%' #‘%’表示任意ip都可以连接数据库
   ports:
   - "3306:3306"
   restart: always
    
  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app       #./表示在当前目录下的app目录
      - ~/.m2:/root/.m2  #~/.m2表示在root下创建.m2文件夹映射
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker